### PR TITLE
fix: support old versions of Firefox in install page

### LINKED ISSUE #276: bug: NS_ERROR_UNKNOWN_PROTOCOL: No error message
Sentry Issue: [KEYMAN-COM-3Z](https://sentry.keyman.com/organizations/keyman/issues/4235/?referrer=github_integration)

```
NS_ERROR_UNKNOWN_PROTOCOL: No error message
  at startAfterPageLoad_Linux/< (/cdn/deploy/keyboard-search/install.17ea5ad4b65082ad69c1a12060e16f37.js:89:7)
```

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #276.

Ensures we don't try the protocol handler for old versions of Firefox, as older versions would try and load the page and break the install experience. Only version 87.0 and later will be supported for the protocol handler (current version as of writing).

### CODE REVIEW

File: cdn/dev/keyboard-search/install.js [hunk 1]
```diff
@@ -71,6 +78,16 @@ function startAfterPageLoad_Windows(data) {
   }, 10);
 }
 
+function isLegacyFirefoxVersion() {
```
Comment (darcywong00) [inline cdn/dev/keyboard-search/install.js:81]: What about passing in `browser` as a parameter since it's already assigned in l.43?

Comment (mcdurdin) [reply cdn/dev/keyboard-search/install.js:81]: yeah but then I still need to do it in the Linux call so figured it made no real difference...

File: cdn/dev/keyboard-search/install.js [hunk 2]
```diff
@@ -71,6 +78,16 @@ function startAfterPageLoad_Windows(data) {
...
+  const browser = document.documentElement.getAttribute('data-browser');
+  if(browser != "Firefox") return false;
+
+  var match = /Firefox\/(\d+\.\d+)/.exec(navigator.userAgent);
```
Comment (darcywong00) [inline cdn/dev/keyboard-search/install.js:85]: Could the regex determine the FF major version number, and then just compare with integer 87 in l.88?

Comment (mcdurdin) [reply cdn/dev/keyboard-search/install.js:85]: it could, but why?

Comment (darcywong00) [reply cdn/dev/keyboard-search/install.js:85]: I thought it would simplify the version comparison, but nvm

**Review by darcywong00 — APPROVED** [review]
lgtm
